FROM php:8.3-fpm

# Install extensions
RUN docker-php-ext-install pdo_mysql
RUN pecl install -o -f redis \
    &&  rm -rf /tmp/pear \
    &&  docker-php-ext-enable redis

# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Add Composer's global bin directory to the PATH
ENV PATH="$PATH:~/.composer/vendor/bin"

# Expose port 8000 and start php-fpm server
EXPOSE 8000
